# Generated by Django 5.1.2 on 2024-11-01 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique='true', verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Interes',
                'verbose_name_plural': 'Intereses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='users/image_user.png', upload_to='users/')),
                ('location', models.CharField(blank=True, max_length=80, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('interests', models.ManyToManyField(blank='True', null='True', to='accounts.interest', verbose_name='Intereses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['-id'],
            },
        ),
    ]
